"""Shell completion scripts for openconnect-saml.

Generates static completion scripts for bash, zsh, and fish.
Includes completion for subcommands, flags, and profile names.
"""

import sys
from pathlib import Path

from openconnect_saml import config


def _get_profile_names():
    """Get list of profile names from config for dynamic completion."""
    try:
        cfg = config.load()
        return [name for name, _ in cfg.list_profiles()]
    except Exception:
        return []


def _bash_completion():
    """Generate bash completion script."""
    return """# openconnect-saml bash completion
# Generated by: openconnect-saml completion bash
# Install: openconnect-saml completion bash > ~/.local/share/bash-completion/completions/openconnect-saml
#   or:    openconnect-saml completion install

_openconnect_saml() {
    local cur prev words cword
    _init_completion || return

    local subcommands="connect profiles status completion service"
    local profiles_actions="list add remove"
    local completion_shells="bash zsh fish install"
    local connect_flags="--server --proxy --headless --browser --authgroup --usergroup
        --authenticate --browser-display-mode --on-connect --on-disconnect
        --ac-version --log-level --user --reset-credentials --totp-source
        --2fauth-url --2fauth-token --2fauth-account-id --reconnect
        --max-retries --no-sudo --csd-wrapper --ssl-legacy --timeout
        --window-size --profile --profile-selector --version --help"

    # Get saved profile names
    local profile_names
    profile_names=$(openconnect-saml completion _profiles 2>/dev/null || echo "")

    case "${words[1]}" in
        connect)
            if [[ ${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "${profile_names} ${connect_flags}" -- "${cur}") )
            else
                COMPREPLY=( $(compgen -W "${connect_flags}" -- "${cur}") )
            fi
            return ;;
        profiles)
            if [[ ${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "${profiles_actions}" -- "${cur}") )
            elif [[ ${cword} -eq 3 ]]; then
                case "${words[2]}" in
                    remove)
                        COMPREPLY=( $(compgen -W "${profile_names}" -- "${cur}") )
                        ;;
                esac
            fi
            return ;;
        status)
            COMPREPLY=( $(compgen -W "--watch -w" -- "${cur}") )
            return ;;
        completion)
            COMPREPLY=( $(compgen -W "${completion_shells}" -- "${cur}") )
            return ;;
        service)
            COMPREPLY=( $(compgen -W "install uninstall start stop status logs" -- "${cur}") )
            return ;;
    esac

    # Top-level completion
    if [[ ${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${subcommands} ${connect_flags}" -- "${cur}") )
    else
        COMPREPLY=( $(compgen -W "${connect_flags}" -- "${cur}") )
    fi
}

complete -F _openconnect_saml openconnect-saml
"""


def _zsh_completion():
    """Generate zsh completion script."""
    return """#compdef openconnect-saml
# openconnect-saml zsh completion
# Generated by: openconnect-saml completion zsh
# Install: openconnect-saml completion zsh > ~/.zsh/completions/_openconnect-saml
#   or:    openconnect-saml completion install

_openconnect_saml_profiles() {
    local profiles
    profiles=(${(f)"$(openconnect-saml completion _profiles 2>/dev/null)"})
    _describe 'profile' profiles
}

_openconnect_saml() {
    local -a subcommands
    subcommands=(
        'connect:Connect to a VPN profile or server'
        'profiles:Manage VPN profiles'
        'status:Show VPN connection status'
        'completion:Generate shell completions'
        'service:Manage systemd VPN service'
    )

    local -a connect_args
    connect_args=(
        '(-s --server)'{-s,--server}'[VPN server]:server:'
        '--proxy[Use proxy]:proxy:'
        '--headless[No GUI]'
        '--browser[Browser backend]:backend:(qt chrome headless)'
        '(-u --user)'{-u,--user}'[Username]:user:'
        '--reconnect[Auto-reconnect]'
        '--max-retries[Max retries]:retries:'
        '--totp-source[TOTP provider]:source:(local 2fauth)'
        '--no-sudo[No sudo]'
        '--ssl-legacy[SSL legacy]'
        '--timeout[Timeout]:seconds:'
        '(-l --log-level)'{-l,--log-level}'[Log level]:level:(ERROR WARNING INFO DEBUG)'
        '(-V --version)'{-V,--version}'[Show version]'
    )

    if (( CURRENT == 2 )); then
        _describe 'command' subcommands
        return
    fi

    case ${words[2]} in
        connect)
            if (( CURRENT == 3 )); then
                _openconnect_saml_profiles
            fi
            _arguments $connect_args
            ;;
        profiles)
            if (( CURRENT == 3 )); then
                local -a actions
                actions=('list:List profiles' 'add:Add a profile' 'remove:Remove a profile')
                _describe 'action' actions
            elif (( CURRENT == 4 )); then
                case ${words[3]} in
                    remove) _openconnect_saml_profiles ;;
                    add) _message 'profile name' ;;
                esac
            fi
            ;;
        status)
            _arguments '--watch[Live update]' '-w[Live update]'
            ;;
        completion)
            if (( CURRENT == 3 )); then
                local -a shells
                shells=('bash' 'zsh' 'fish' 'install')
                _describe 'shell' shells
            fi
            ;;
        service)
            if (( CURRENT == 3 )); then
                local -a actions
                actions=('install' 'uninstall' 'start' 'stop' 'status' 'logs')
                _describe 'action' actions
            fi
            ;;
        *)
            _arguments $connect_args
            ;;
    esac
}

_openconnect_saml "$@"
"""


def _fish_completion():
    """Generate fish completion script."""
    return """# openconnect-saml fish completion
# Generated by: openconnect-saml completion fish
# Install: openconnect-saml completion fish > ~/.config/fish/completions/openconnect-saml.fish
#   or:    openconnect-saml completion install

# Subcommands
set -l commands connect profiles status completion service

# Disable file completion by default
complete -c openconnect-saml -f

# Top-level subcommands
complete -c openconnect-saml -n "not __fish_seen_subcommand_from $commands" -a connect -d "Connect to VPN"
complete -c openconnect-saml -n "not __fish_seen_subcommand_from $commands" -a profiles -d "Manage profiles"
complete -c openconnect-saml -n "not __fish_seen_subcommand_from $commands" -a status -d "Show status"
complete -c openconnect-saml -n "not __fish_seen_subcommand_from $commands" -a completion -d "Shell completions"
complete -c openconnect-saml -n "not __fish_seen_subcommand_from $commands" -a service -d "Systemd service"

# connect subcommand
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -s s -l server -d "VPN server" -x
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l proxy -d "Proxy server" -x
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l headless -d "No GUI"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l browser -d "Browser" -xa "qt chrome headless"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -s u -l user -d "Username" -x
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l reconnect -d "Auto-reconnect"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l totp-source -d "TOTP source" -xa "local 2fauth"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l no-sudo -d "No sudo"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l ssl-legacy -d "SSL legacy"
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect" -l timeout -d "Timeout" -x

# Dynamic profile names for connect
complete -c openconnect-saml -n "__fish_seen_subcommand_from connect; and not __fish_seen_subcommand_from (openconnect-saml completion _profiles 2>/dev/null)" -xa "(openconnect-saml completion _profiles 2>/dev/null)"

# profiles subcommand
complete -c openconnect-saml -n "__fish_seen_subcommand_from profiles; and not __fish_seen_subcommand_from list add remove" -a list -d "List profiles"
complete -c openconnect-saml -n "__fish_seen_subcommand_from profiles; and not __fish_seen_subcommand_from list add remove" -a add -d "Add profile"
complete -c openconnect-saml -n "__fish_seen_subcommand_from profiles; and not __fish_seen_subcommand_from list add remove" -a remove -d "Remove profile"
complete -c openconnect-saml -n "__fish_seen_subcommand_from profiles; and __fish_seen_subcommand_from remove" -xa "(openconnect-saml completion _profiles 2>/dev/null)"

# status subcommand
complete -c openconnect-saml -n "__fish_seen_subcommand_from status" -s w -l watch -d "Live update"

# completion subcommand
complete -c openconnect-saml -n "__fish_seen_subcommand_from completion" -xa "bash zsh fish install"

# service subcommand
complete -c openconnect-saml -n "__fish_seen_subcommand_from service" -xa "install uninstall start stop status logs"

# Global flags
complete -c openconnect-saml -s V -l version -d "Show version"
complete -c openconnect-saml -s h -l help -d "Show help"
"""


def _install_completions():
    """Auto-install completion scripts for detected shells."""
    installed = []

    # Bash
    bash_dir = Path.home() / ".local" / "share" / "bash-completion" / "completions"
    bash_dir.mkdir(parents=True, exist_ok=True)
    bash_path = bash_dir / "openconnect-saml"
    bash_path.write_text(_bash_completion())
    installed.append(f"bash → {bash_path}")

    # Zsh
    zsh_dir = Path.home() / ".zsh" / "completions"
    zsh_dir.mkdir(parents=True, exist_ok=True)
    zsh_path = zsh_dir / "_openconnect-saml"
    zsh_path.write_text(_zsh_completion())
    installed.append(f"zsh  → {zsh_path}")
    # Check if zsh fpath includes this dir
    print("Note: Ensure your .zshrc includes: fpath=(~/.zsh/completions $fpath)")

    # Fish
    fish_dir = Path.home() / ".config" / "fish" / "completions"
    fish_dir.mkdir(parents=True, exist_ok=True)
    fish_path = fish_dir / "openconnect-saml.fish"
    fish_path.write_text(_fish_completion())
    installed.append(f"fish → {fish_path}")

    print("Installed shell completions:")
    for entry in installed:
        print(f"  {entry}")
    print("\nRestart your shell or source the completion file to activate.")
    return 0


def handle_completion_command(args):
    """Handle the 'completion' subcommand."""
    shell_type = args.shell_type

    # Hidden subcommand for dynamic profile completion
    if shell_type == "_profiles":
        names = _get_profile_names()
        for name in names:
            print(name)
        return 0

    if shell_type == "bash":
        print(_bash_completion())
    elif shell_type == "zsh":
        print(_zsh_completion())
    elif shell_type == "fish":
        print(_fish_completion())
    elif shell_type == "install":
        return _install_completions()
    else:
        print(f"Unknown shell: {shell_type}", file=sys.stderr)
        return 1

    return 0
